// Illustrative client quotes drafted from each project's context.
// Replace these with approved client feedback before treating them
// as endorsements — attribution is role + project only, no real names.
export const testimonials = [
  {
    id: 1,
    quote: "Feels less like a CRM, more like a control room.",
    author: "Product Lead",
    project: "Wasla CRM",
    href: "https://wasla-crm.vercel.app/en/login",
  },
  {
    id: 2,
    quote: "Bookings, SOS dispatch, payments — one reliable flow.",
    author: "Product Owner",
    project: "Nabdh",
  },
  {
    id: 3,
    quote: "Production-ready under real government constraints.",
    author: "Project Supervisor",
    project: "Medical System",
  },
  {
    id: 4,
    quote: "The 3D labs make learning feel like playing.",
    author: "Academic Director",
    project: "CyrusLearn",
    href: "https://stagging-cylearn.vercel.app/",
  },
  {
    id: 5,
    quote: "We finally see security events the moment they happen.",
    author: "Operations Manager",
    project: "Tailgating Detection",
    href: "https://github.com/Zahrannnn/tailgating-frontend",
  },
  {
    id: 6,
    quote: "Dollhouse to panorama without a single reload.",
    author: "Engineering Team",
    project: "RICOH 3D Viewer",
    href: "https://www.ricoh-europe.com",
  },
  {
    id: 7,
    quote: "Arabic RTL that actually feels native.",
    author: "Store Owner",
    project: "OZ Storefront",
    href: "https://oz-storefront.vercel.app",
  },
  {
    id: 8,
    quote: "From job board to tailored CV in one click.",
    author: "Beta User",
    project: "AI Job Searcher",
    href: "https://github.com/Zahrannnn/ai-job-searcher",
  },
  {
    id: 9,
    quote: "Two languages, one dashboard, zero friction.",
    author: "Operations Lead",
    project: "NedSwiss CRM",
    href: "https://stage-nedswiss.vercel.app/",
  },
  {
    id: 10,
    quote: "The scroll animations made our brand feel premium.",
    author: "Managing Director",
    project: "NedSwiss Website",
    href: "https://ned-swiss.ch/",
  },
  {
    id: 11,
    quote: "Invoice chaos turned into a clean, trackable flow.",
    author: "Finance Manager",
    project: "AGL Invoices",
  },
  {
    id: 12,
    quote: "Annotation that used to take hours now takes minutes.",
    author: "Data Lead",
    project: "Qalam Vision",
  },
  {
    id: 13,
    quote: "Accuracy we can trust, in Arabic and English.",
    author: "Product Lead",
    project: "Wasla Moderation API",
    href: "https://mohameddda-moderator-api.hf.space/docs",
  },
  {
    id: 14,
    quote: "Clean layers, real-time events, payments that just work.",
    author: "Backend Lead",
    project: "Wasla Backend",
    href: "http://waslacrm.runasp.net/",
  },
  {
    id: 15,
    quote: "Three languages, one checkout, zero confusion.",
    author: "Founder",
    project: "Translation Platform",
  },
  {
    id: 16,
    quote: "Our brand finally looks the way it deserves.",
    author: "Founder",
    project: "ARME Egypt",
    href: "https://www.armegypt.com/",
  },
  {
    id: 17,
    quote: "Fast, clean, and exactly what we asked for.",
    author: "Founder",
    project: "Standby Egypt",
    href: "https://standby-eg.com/",
  },
  {
    id: 18,
    quote: "A valet experience that starts on the website.",
    author: "Founder",
    project: "Best Valet",
    href: "https://best-valet.vercel.app/",
  },
  {
    id: 19,
    quote: "Sharp product site, sharp deadlines.",
    author: "Product Manager",
    project: "Planit Software",
    href: "https://planit-software.vercel.app/",
  },
  {
    id: 20,
    quote: "From idea to web app faster than we imagined.",
    author: "Founder",
    project: "Notecker",
    href: "https://notecker.vercel.app/",
  },
];
